### ISSUE TITLE
Readiness probe error not handled due to php-fpm-healthcheck timeout

### ISSUE THREAD

**Issue by xriser** [renatomefi/php-fpm-healthcheck#41]
When php-fpm stuck and didn't respond, php-fpm-healthckeck can't handle this, and timeouts to connect to the port.

`root@deployment-php-5bddfd7964-7ctmf:/app# php-fpm-healthcheck -v
Trying to connect to php-fpm via: localhost:9000/status
^C`
So, php-fpm-healthcheck doesn't return fail status in a reasonable time.

Since K8s doesn't handle timeouts healthcheck, it doesn't work. Because Kubernetes remove the pod from service only when heathcheck returning fail event. 
`
Readiness probe errored: rpc error: code = DeadlineExceeded desc = context deadline exceeded
`
Readiness probe errored, but pod didn't remove from services. 

Is there any way to setup a reasonable timeout to connect to the PHP port for the php-fpm-healthcheck?

**Comment by chrispage1** [comment]
I'm getting the same - makes it a little useless when PHP-FPM stops responding

**Comment by chrispage1** [comment]
Just to update with this one for anyone else searching, I managed to resolve using BusyBox `timeout` command in my Kubernetes liveness probe...

```yaml
livenessProbe:
  exec:
    command:
     - timeout
     - "1"
     - php-fpm-healthcheck
     - --listen-queue=15 # fails if there are more than 10 processes waiting in the fpm queue
```

This means that if php-fpm-healthcheck doesn't return success within 1 second it'll assume its dead.
